PaulSchool/Models/Attendance.cs
namespace PaulSchool.Models
{
    public class Attendance
    {
        public int AttendanceID { get; set; }

        public int CourseID { get; set; }

        public int StudentID { get; set; }

        public int AttendanceDay { get; set; }

        public bool Present { get; set; }

        public virtual Course Course { get; set; }

        public virtual Student Student { get; set; }
    }
}

PaulSchool/Controllers/AttendanceController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="AttendanceController.cs" company="LostTie LLC">
//   Copyright (c) Lost Tie LLC.  All rights reserved.
//   This code and information is provided "as is" without warranty of any kind, either expressed or implied, including but not limited to the implied warranties of merchantability and fitness for a particular purpose.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
namespace PaulSchool.Controllers
{
    #region

    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;
    using System.Web.Mvc;

    using PaulSchool.Models;
    using PaulSchool.Resources;
    using PaulSchool.ViewModels;

    #endregion

    public class AttendanceController : Controller
    {
        #region Fields

        private readonly SchoolContext db = new SchoolContext();

        #endregion

        #region Public Methods and Operators

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult ArchiveCourse(int id)
        {
            Course course = this.db.Courses.Find(id);
            course.Archived = true;
            this.BuildNotification(course);
            this.db.SaveChanges();
            return this.RedirectToAction("Message", new { message = "You have added the course to the archive." });
        }

        public ActionResult AttendanceView(int id)
        {
            List<Attendance> attendanceItemsList = this.AttendanceItemsList(id);
            List<Student> studentList = this.StudentList(id);
            IEnumerable<Enrollment> enrollmentList = this.EnrollmentList(id);
            Course course = this.db.Courses.FirstOrDefault(p => p.CourseID == id);
            List<int> attDayList = AttDayList(course);

            var model = new AttendanceReportViewModel
                {
                    AttendanceDays = attDayList, 
                    Students = studentList, 
                    Enrollments = enrollmentList, 
                    Attendances = attendanceItemsList, 
                    CourseId = id, 
                    Course = course
                };
            this.ViewBag.CourseName = course.Title;
            return View(model);
        }

        public ActionResult CompleteCourse(int id)
        {
            Course course = this.db.Courses.Find(id);
            course.Completed = true;

            this.BuildNotificationForAdmin(course);
            this.BuildNotificationForInstructor(course);
            this.BuildNotificationsForStudents(course);
            this.db.SaveChanges();

            return this.RedirectToAction("Message", new { message = "You have completed the course." });
        }

        public ActionResult EditComment(int studentId, int courseId)
        {
            Enrollment enrollment =
                this.db.Enrollments.FirstOrDefault(s => s.StudentID == studentId && s.CourseID == courseId);
            if (enrollment != null && enrollment.Course.Completed)
            {
                RedirectToAction("Error");
            }
            else
            {
                var model = new EditCommentGradeViewModel
                    {
                        EnrollmentID = enrollment.EnrollmentID, 
                        Student = enrollment.Student, 
                        Grades =
                            new List<SelectListItem>
                                {
                                    new SelectListItem
                                        {
                                            Text = PaulSchoolResource.AttendanceController_EditComment_Incomplete, 
                                            Value = PaulSchoolResource.AttendanceController_EditComment_Incomplete
                                        }, 
                                    new SelectListItem
                                        {
                                            Text = PaulSchoolResource.AttendanceController_EditComment_Pass, 
                                            Value = PaulSchoolResource.AttendanceController_EditComment_Pass
                                        }, 
                                    new SelectListItem
                                        {
                                            Text = PaulSchoolResource.AttendanceController_EditComment_Fail, 
                                            Value = PaulSchoolResource.AttendanceController_EditComment_Fail
                                        }, 
                                }, 
                        Grade = enrollment.Grade, 
                        Comments = enrollment.Comments
                    };
                return View(model);
            }

            return View("Error");
        }

        [HttpPost]
        public ActionResult EditComment(Enrollment enrollmentComment)
        {
            if (this.ModelState.IsValid)
            {
                this.db.Entry(enrollmentComment).State = EntityState.Modified;
                this.db.SaveChanges();
                return this.RedirectToAction("AttendanceView", new { id = enrollmentComment.CourseID });
            }

            return View(enrollmentComment);
        }

        public ActionResult EditIndividualAttendance(int id, int studentId)
        {
            List<Attendance> attendanceItemsList = this.AttendanceItemsList(id);
            List<Student> studentList = this.SingleStudentList(id, studentId);
            IEnumerable<Enrollment> enrollmentList = this.SingleStudentEnrollmentList(id, studentId);
            Course course = this.db.Courses.FirstOrDefault(p => p.CourseID == id);
            List<int> attDayList = AttDayList(course);

            var model = new AttendanceReportViewModel
                {
                    AttendanceDays = attDayList, 
                    Students = studentList, 
                    Enrollments = enrollmentList, 
                    Attendances = attendanceItemsList, 
                    CourseId = id
                };

            if (course.Completed)
            {
                RedirectToAction("Error");
            }
            else
            {
                return View(model);
            }

            return View("Error");
        }

        public ActionResult Index()
        {
            return this.View();
        }

        public ViewResult Message(string message)
        {
            this.ViewBag.message = message;
            return this.View();
        }

        public ActionResult StudentDetails(int id)
        {
            //// Generates list of Attendances specifically for current Course
            IQueryable<Attendance> attendanceItems = this.db.Attendance.Where(s => s.CourseID == id);
            List<Attendance> attendanceItemsList = attendanceItems.ToList();

            //// End of generating list of Attendances

            //// Generates list of Students (should be one only one student)
            IQueryable<Student> student = this.db.Students.Where(a => a.UserName == this.User.Identity.Name);
            List<Student> studentList = student.ToList();

            //// End of generating list of Students

            //// Generates list of AttendingDays specifically for current Course
            Course course = this.db.Courses.FirstOrDefault(p => p.CourseID == id);
            var attDayList = new List<int>();
            for (int i = 0; i < course.AttendingDays; i++)
            {
                attDayList.Add(i + 1);
            }

            //// End of generating list of AttendingDays
            Enrollment enrollment =
                this.db.Enrollments.FirstOrDefault(
                    q => q.Student.UserName == this.User.Identity.Name && q.CourseID == id);

            var model = new AttendanceReportViewModel
                {
                    AttendanceDays = attDayList, 
                    Students = studentList, 
                    
                    
                    ////should be only one student for this ActionResult
                    Attendances = attendanceItemsList, 
                    Comments = enrollment.Comments, 
                    Paid = enrollment.Paid, 
                    Course = course, 
                    SingleStudentEnrollment = enrollment
                };

            return View(model);
        }

        [Authorize(Roles = "SuperAdministrator")]
        public ActionResult UnArchiveCourse(int id)
        {
            Course course = this.db.Courses.Find(id);
            course.Archived = false;
            this.db.SaveChanges();
            return this.RedirectToAction("Message", new { message = "You have removed the course from the archive." });
        }

        [Authorize(Roles = "SuperAdministrator")]
        public ActionResult UnCompleteCourse(int id)
        {
            Course course = this.db.Courses.Find(id);
            course.Completed = false;
            this.db.SaveChanges();
            return this.RedirectToAction("Message", new { message = "You have set the course to incomplete." });
        }

        [HttpPost]
        public bool UpdateAttendance(int userId, int attendanceDay, int courseId, int present)
        {
            //// Taking the attendence of corresponding userId
            Attendance attendance =
                this.db.Attendance.FirstOrDefault(
                    s => s.StudentID == userId && s.CourseID == courseId && s.AttendanceDay == attendanceDay);
            if (attendance != null)
            {
                attendance.Present = Convert.ToBoolean(present);
                this.db.Entry(attendance).State = EntityState.Modified;
            }

            this.db.SaveChanges();
            return true;
        }

        public ActionResult ViewComment(int studentId, int courseId)
        {

PaulSchool/Views/Attendance/ArchivedCourse.cshtml
@{
    ViewBag.Title = "ArchivedCourse";
}

<h2>Archived Course</h2>
<p>
    You have marked this Course as Archived.
</p>

@Html.ActionLink("Home", "Index", "Home")

PaulSchool/Views/Attendance/AttendanceView.cshtml
@using PaulSchool.Models
@using PaulSchool.Resources
@model PaulSchool.ViewModels.AttendanceReportViewModel
@{
    ViewBag.Title = "AttendanceView";

}
<h2>
    Details for @ViewBag.CourseName
</h2>
<table>
    <thead>
        <tr>
            <th>
                Attendance Day
            </th>
            @foreach (int attendanceDay in Model.AttendanceDays)
            {
                <th>@attendanceDay
                </th>
            }
            <th>
                Edit Student's Attendance
            </th>
            <th>
                Grade
            </th>
            <th>
                @{
                    if (Model.Course.Completed)
                    {
                        <div>
                            View Grade / Comments
                        </div>
                    }
                    else
                    {
                        <div>
                            Edit Grade / Comments
                        </div>
                    }

                }
                
            </th>
            @{
                if (Model.Course.Completed)
                {
                    <th>
                        Certificate
                    </th>
                }
            }
        </tr>
    </thead>
    <tbody id="@Model.CourseId">
        @foreach (Student student in Model.Students)
        {
            <tr id="@student.StudentID">
                <td>@student.LastName</td>
                @foreach (int attendanceDay in Model.AttendanceDays)
                {
                    <td id="@attendanceDay" class="attendance">
                        <span>
                            @Model.IsPresent(student, attendanceDay)
                        </span>
                    </td>
                }
                <td>
                    @{
                        if (Model.Course.Completed)
                        {
                            <div>
                                Course is completed, unable to edit.
                            </div>
                        }
                        else
                        {
                            @Html.ActionLink("edit", "EditIndividualAttendance", new { id = Model.CourseId, studentId = student.StudentID })
                        }

                    }
                </td>
                <td>
                    @Html.Raw(Model.Enrollments.FirstOrDefault(o => o.StudentID == student.StudentID).Grade)
                </td>
                <td>
                    @{
                        if (Model.Course.Completed)
                        {
                            <div>
                                @Html.ActionLink("View Grade / Comments", "ViewComment", new { studentId = student.StudentID, Model.CourseId })  
                            </div>
                        }
                        else
                        {
                            @Html.ActionLink("Edit Grade / Comments", "EditComment", new { studentId = student.StudentID, Model.CourseId })
                        }

                    }
                </td>
                @{
                if (Model.Course.Completed)
                {
                    <td>
                        @Html.ActionLink("Standard", "CertificateOfAttendance", "Certificate", new { id = Model.Enrollments.First(o => o.Student.StudentID == student.StudentID).EnrollmentID }, null) 
                        <span> or </span>
                        @Html.ActionLink("With line for signature", "CertificateOfAttendanceWSig", "Certificate", new { id = Model.Enrollments.First(o => o.Student.StudentID == student.StudentID).EnrollmentID }, null)
                    </td>
                }
            }
            </tr>
        }
    </tbody>
</table>
@{
    if (User.IsInRole("Instructor") || User.IsInRole("Administrator") || User.IsInRole("SuperAdministrator"))
    {
        <div>
            @{
                if (Model.Course.Completed)
                {
                    <p>
                        This course is complete.
                    </p>
                    if (User.IsInRole("SuperAdministrator"))
                    {
                        @Html.ActionLink("Click here to mark course as incomplete", "UnCompleteCourse", new { id = Model.CourseId }, new { onclick = "return confirm('Are you sure you are ready to mark this Course as Incomplete?');" })
                    }
                }
                else
                {
                    if ((User.IsInRole("Administrator") || User.IsInRole("SuperAdministrator")) || Model.Course.EndDate < DateTime.Now )
                    {
                        <p>
                            @Html.ActionLink("Click here", "CompleteCourse", new {id = Model.CourseId}, new {onclick = "return confirm('Are you sure you are ready to mark this Course as Complete?  You will not be able to edit the attendance, grades, or comments after you do this.');"}) to mark this Course as "Complete."  Doing so will make this Course uneditable.
                        </p>
                    }
                    else
                    {
                        <p>
                            As an Instructor you will have the option to mark this course as completed with a link that will appear here after the end-date of the course has passed.
                        </p>
                    }
                }

            }
            @{
                if (User.IsInRole("Administrator") || User.IsInRole("SuperAdministrator"))
                {
                    if (Model.Course.Archived)
                    {
                        <p>
                            This course is archived.
                        </p>
                        if (User.IsInRole("SuperAdministrator"))
                        {
                            @Html.ActionLink("Click here to remove course from the archive", "UnArchiveCourse", new { id = Model.CourseId }, new { onclick = "return confirm('Are you sure you are ready to UnArchive this Course?');" })
                        }
                    }
                    else
                    {
                        <div>
                            <p>
                                @Html.ActionLink("Click here", "ArchiveCourse", new { id = Model.CourseId }, new { onclick = "return confirm('Are you sure you are ready to Archive this Course?  Administrators will not be able to edit this Course's attendance, grades, or comments after you do this.');" }) to Archive this Course."  Doing so will make this Course uneditable by Administrators.
                            </p>
                        </div>
                    }
                }

            }
        </div>
    }

}

<script type="text/javascript">
    var userId;
    var attendanceDay;
    var isPresent;
    var updateAttendanceUrl;
    var absentText;
    var presentText;
    var courseId;
    $(document).ready(function (event) {
        $(".page *").highlight("absent", "redtext");
    });
    function UpdateAttendance(present) {
        url = updateAttendanceUrl;
        $.ajax({
            type: "POST",
            url: url,
            data: "userId=" + userId + "&attendanceDay=" + attendanceDay + "&courseId=" + courseId + "&present=" + present,
            success: function (data) {
                if (isPresent == absentText) {
                    $('#' + userId).find('.currentClass').text(presentText).removeAttr('class');
                } else {
                    $('#' + userId).find('.currentClass').text(absentText).removeAttr('class').addClass("redtext");
                }
                return true;
            }
        });
    }

    jQuery.fn.highlight = function (str, className) {
        var regex = new RegExp(str, "gi");
        return this.each(function () {
            $(this).contents().filter(function () {
                return this.nodeType == 3 && regex.test(this.nodeValue);
            }).replaceWith(function () {
                return (this.nodeValue || "").replace(regex, function (match) {
                    return "<span class=\"" + className + "\">" + match + "</span>";
                });
            });
        });
    };

</script>

PaulSchool/Views/Attendance/CompletedCourse.cshtml
@{
    ViewBag.Title = "CompletedCourse";
}

<h2>Completed Course</h2>
<p>
    You have marked this Course as Complete.
</p>

@Html.ActionLink("Home", "Index", "Home")

PaulSchool/Views/Attendance/EditComment.cshtml
@model PaulSchool.ViewModels.EditCommentGradeViewModel

@{
    ViewBag.Title = "Edit Grade and Comment";
}

<h2>Edit Grade and Comment</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        @*<legend></legend>*@
        
        @Html.HiddenFor(model => model.EnrollmentID)
        
        <div class="editor-label">
            @Html.DisplayText("Name")
        </div>
        <div>
            @Html.DisplayFor(model => model.Student.FirstMidName) @Html.DisplayFor(model => model.Student.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Grade)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Grade, Model.Grades)
            @Html.ValidationMessageFor(model => model.Grade)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comments)*
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Comments)
            @Html.ValidationMessageFor(model => model.Comments)
        </div>
        
        <p>
            *Note that comments are visible by the Student and Instructor involved as well as Admin.
        </p>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}


PaulSchool/Views/Attendance/EditIndividualAttendance.cshtml
@model PaulSchool.ViewModels.AttendanceReportViewModel
@{
    ViewBag.Title = "AttendanceView";
}
<script src="@Url.Content("~/Scripts/AttendanceForm.js")" type="text/javascript"></script>
<h2>
    AttendanceView</h2>
    <p>Click on an attendance value to toggle it between "present" and "absent"</p>
<table>
    <thead>
        <tr>
            <th>
                Attendance Day
            </th>
            @foreach (var attendanceDay in Model.AttendanceDays)
            {
                <th>@attendanceDay
                </th>
            }
        </tr>
    </thead>
    <tbody id="@Model.CourseId">
        @foreach (var student in Model.Students)
        {
            <tr id="@student.StudentID">
                <td>@student.LastName</td>
                @foreach (var attendanceDay in Model.AttendanceDays)
                {
                    <td id="@attendanceDay" class="attendance">
                        <span>
                            @Model.IsPresent(student, attendanceDay)
                        </span>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>
<p>
    @Html.ActionLink("Click here to return to the details of the course (your changes are instantly saved)", "AttendanceView", new { id = Model.CourseId })
</p>
<p>
    *If you are having difficulty editing attendance values, please ensure that JavaScript is enabled in your browser.
</p>
<script type="text/javascript">
    //absentText = $.trim('@PaulSchool.Resources.PaulSchoolResource.Absent_Text').toLowerCase();
    absentText = ('@PaulSchool.Resources.PaulSchoolResource.Absent_Text').toLowerCase();
    presentText = $.trim('@PaulSchool.Resources.PaulSchoolResource.Present_Text').toLowerCase();
    updateAttendanceUrl = '@Url.Action("UpdateAttendance", "Attendance")';
</script>

PaulSchool/Views/Attendance/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Attendance Index";
}

<h2>Attendance Index</h2>

PaulSchool/Views/Attendance/List.cshtml
@model IEnumerable<dynamic>
@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<div>
@{
    var grid = new WebGrid(Model, defaultSort: "Name");
}
        
    @grid.GetHtml()

</div>

PaulSchool/Views/Attendance/Message.cshtml
@{
    ViewBag.Title = "Message";
}

<h2>Message</h2>
<p>@ViewBag.message</p>

PaulSchool/Views/Attendance/StudentDetails.cshtml
@using PaulSchool.Models
@using PaulSchool.Helpers
@model PaulSchool.ViewModels.AttendanceReportViewModel

@{
    ViewBag.Title = "StudentDetails";
}
<script src="@Url.Content("~/Scripts/AttendanceForm.js")" type="text/javascript"></script>
<h2>Your attendance details for @Model.Course.Title:</h2>
<p>    
    @{
        if (!string.IsNullOrEmpty(TempData["tempMessage"] as string))
        {
            <b class="error">@TempData["tempMessage"].ToString()</b>
        }
    }
</p>
<p>
    @{
        if (Model.Paid == false)
        {
            <h1>You have not paid for this course.  The application fee is @Model.Course.Cost.ToString("c"). You can pay this fee using the Paypal link below, or by mailing check or money order to St. Paul School of Catechesis, 620 Lipan, Corpus Christi, TX 78401.</h1>
            var actualCost = Model.Course.Cost;
            @Html.PayPalButton(false,
                               HtmlHelpers.EButtonType.PayNow,
                               "Tvillegas@diocesecc.org",
                               "Enrollment fee for " + Model.Course.Title,
                               Model.SingleStudentEnrollment.EnrollmentID.ToString(),
                               (float)actualCost,
                               HtmlHelpers.ECurrencyCode.USD,
                               "http://localhost.com/home/complete",
                               "http://localhost.com/home/cancel",
                               "http://24.155.210.182/paulschool/paypal/ipn")
        }
    }
</p>

<div>
    <p>The first day of class is @Model.Course.StartDate and the last day is @Model.Course.EndDate . </p>
    <p>This class starts at @Model.Course.StartTime and ends at @Model.Course.EndTime .</p>
</div>
<table>
    <thead>
        <tr>
            <th>Attendance Day</th>
            @foreach (int attendanceDay in Model.AttendanceDays)
            {
                <th>@attendanceDay</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (Student student in Model.Students)
        {
            <tr>
                <td>@student.LastName</td>
                @foreach (int attendanceDay in Model.AttendanceDays)
                {
                    <td>@Model.IsPresent(student, attendanceDay)</td>
                }
            </tr>
        }
    </tbody>
</table>

<h4>Your grade for the course:</h4>
@Model.SingleStudentEnrollment.Grade

<h4>Comments made by your Instructor:</h4>
@Model.Comments

@{ if (Model.Paid == true)
   {
       <div>*There is no payment due for this course.</div>
   }}

PaulSchool/Views/Attendance/ViewComment.cshtml
@model PaulSchool.ViewModels.EditCommentGradeViewModel

@{
    ViewBag.Title = "ViewComment";
}

<h2>ViewComment</h2>

<fieldset>
    <legend>Viewing Grade / Comments</legend>

    <div class="display-label">Student Name:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.FirstMidName) @Html.DisplayFor(model => model.Student.LastName)
    </div>

    <div class="display-label">Grade</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Grade)
    </div>

    <div class="display-label">Comments</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comments)
    </div>
</fieldset>