PaulSchool/Areas/MvcMembership/Models/UserAdministration/DetailsViewModel.cs
using System.Collections.Generic;
using System.Web.Security;

namespace SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration
{
	public class DetailsViewModel
	{
		#region StatusEnum enum

		public enum StatusEnum
		{
			Offline,
			Online,
			LockedOut,
			Unapproved
		}

		#endregion

		public string DisplayName { get; set; }
		public StatusEnum Status { get; set; }
		public MembershipUser User { get; set; }
		public bool CanResetPassword { get; set; }
		public bool RequirePasswordQuestionAnswerToResetPassword { get; set; }
		public IDictionary<string, bool> Roles { get; set; }
		public bool IsRolesEnabled { get; set; }
	}
}

PaulSchool/Models/Student.cs
using System;
using System.Collections.Generic;

namespace PaulSchool.Models
{
    public class Student
    {
        public int StudentID { get; set; }

        public string LastName { get; set; }

        public string FirstMidName { get; set; }

        public string Email { get; set; }

        public string StreetAddress { get; set; }

        public string City { get; set; }

        public string State { get; set; }

        public string ZipCode { get; set; }

        public string Phone { get; set; }

        public string DateOfBirth { get; set; }

        public string ParishAffiliation { get; set; }

        public string MinistryInvolvement { get; set; } // drop-down including a blank customizable field

        public DateTime EnrollmentDate { get; set; }

        public virtual ICollection<Enrollment> Enrollments { get; set; }
        //if a given Student row in the database has two related Enrollment rows (rows that contain that student's primary key value in their StudentID foreign key column), that Student entity's Enrollments navigation property will contain those two Enrollment entities.

        public string UserName { get; set; }
    }
}

PaulSchool/Controllers/CourseController.cs
namespace PaulSchool.Controllers
{
    #region

    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Diagnostics;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Security;

    using PagedList;

    using PaulSchool.Models;
    using PaulSchool.ViewModels;

    #endregion

    [Authorize]
    public class CourseController : Controller
    {
        #region Fields

        private readonly SchoolContext db = new SchoolContext();

        #endregion

        #region Public Methods and Operators

        public ViewResult ApplyToCourse(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = string.IsNullOrEmpty(sortOrder) ? "Title desc" : string.Empty;
            ViewBag.StartDateSortParm = sortOrder == "StartDate" ? "StartDate desc" : "StartDate";
            ViewBag.CreditsSortParm = sortOrder == "Credits" ? "Credits desc" : "Credits";
            ViewBag.InstructorSortParm = sortOrder == "Instructor" ? "Instructor desc" : "Instructor";
            ViewBag.AttendingDaysSortParm = sortOrder == "AttendingDays" ? "AttendingDays desc" : "AttendingDays";
            ViewBag.AttendanceCapSortParm = sortOrder == "AttendanceCap" ? "AttendanceCap desc" : "AttendanceCap";
            ViewBag.LocationSortParm = sortOrder == "Location" ? "Location desc" : "Location";
            ViewBag.ParishSortParm = sortOrder == "Parish" ? "Parish desc" : "Parish";

            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }
            else
            {
                page = 1;
            }

            ViewBag.CurrentFilter = searchString;

            IQueryable<Course> courses = db.Courses.Where(s => s.Approved && s.Completed == false);

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(s => s.Title.ToUpper().Contains(searchString.ToUpper()));
            }

            switch (sortOrder)
            {
                case "Title desc":
                    courses = courses.OrderByDescending(s => s.Title);
                    break;
                case "StartDate":
                    courses = courses.OrderBy(s => s.StartDate);
                    break;
                case "StartDate desc":
                    courses = courses.OrderByDescending(s => s.StartDate);
                    break;
                case "Credits":
                    courses = courses.OrderBy(s => s.Credits);
                    break;
                case "Credits desc":
                    courses = courses.OrderByDescending(s => s.Credits);
                    break;
                case "Instructor":
                    courses = courses.OrderBy(s => s.Instructor.LastName);
                    break;
                case "Instructor desc":
                    courses = courses.OrderByDescending(s => s.Instructor.LastName);
                    break;
                case "AttendingDays":
                    courses = courses.OrderBy(s => s.AttendingDays);
                    break;
                case "AttendingDays desc":
                    courses = courses.OrderByDescending(s => s.AttendingDays);
                    break;
                case "AttendanceCap":
                    courses = courses.OrderBy(s => s.AttendanceCap);
                    break;
                case "AttendanceCap desc":
                    courses = courses.OrderByDescending(s => s.AttendanceCap);
                    break;
                case "Location":
                    courses = courses.OrderBy(s => s.Location);
                    break;
                case "Location desc":
                    courses = courses.OrderByDescending(s => s.Location);
                    break;
                case "Parish":
                    courses = courses.OrderBy(s => s.Parish);
                    break;
                case "Parish desc":
                    courses = courses.OrderByDescending(s => s.Parish);
                    break;
                default:
                    courses = courses.OrderBy(s => s.Title);
                    break;
            }

            int pageSize = 10;
            int pageNumber = page ?? 1;

            // Find out how many seats are available
            foreach (Course course in courses)
            {
                int count = this.db.Enrollments.Count(o => o.CourseID == course.CourseID);
                int seatsLeft = course.AttendanceCap - count;
                ViewBag.course = seatsLeft;
            }

            return View(courses.ToPagedList(pageNumber, pageSize));
        }

        [Authorize(Roles = "Administrator, SuperAdministrator, Instructor")]
        public ActionResult ApplyToTeach()
        {
            DbSet<CourseTemplates> course = db.CourseTemplates;
            var model = new ApplyCourseViewModel
                {
                    Courses = course.Select(x => new SelectListItem { Value = x.Title, Text = x.Title, }), 
                    StartDate = DateTime.Now, 
                    EndDate = DateTime.Now
                };
            return View(model);
        }

        [HttpPost]
        public ActionResult ApplyToTeach(ApplyCourseViewModel appliedCourse)
        {
            if (ModelState.IsValid)
            {
                Debug.Write(appliedCourse.Cost);
                Instructor instructor = db.Instructors.FirstOrDefault(o => o.UserName == User.Identity.Name);

                if (instructor == null)
                {
                    // If the user is currently not an Instructor, make them one
                    Student currentUser = db.Students.FirstOrDefault(o => o.UserName == User.Identity.Name);

                    // "currentUser" needed to have user's information ( every user should have data in the Student table, 
                    // so their information is stored there)

                    // Creates a new Instructor in the Instructor Table
                    // using the User's information
                    CreatesInstructorDataAndAssignsRole(currentUser);
                }

                Instructor instructorAgain = db.Instructors.FirstOrDefault(o => o.UserName == User.Identity.Name);

                // Have to check the instructor again because if we just created 
                // the instructor there will be "null" in the "instructor" variable
                Course newCourse = BuildCourseData(appliedCourse, instructorAgain);
                Debug.Write(appliedCourse.Cost);
                db.SaveChanges();
                BuildNotificationData(appliedCourse, instructorAgain, newCourse);
                db.SaveChanges();
                TempData["tempMessage"] =
                    "You have successfully applied to teach this course.  A notification has been sent to an administrator so they can review the application.  You will receive a notification when an administrator takes action on your application to teach, this typically takes 1 - 3 business days.";
                return RedirectToAction("Details", new { id = newCourse.CourseID });
            }

            return View("Error");
        }

        [HttpPost]
        public ActionResult ApplyUsingDetails(Course idGetter)
        {
            // try to join course
            Course course = db.Courses.Find(idGetter.CourseID);
            if (course.Approved && !course.Completed)
            {
                Student thisStudent = db.Students.FirstOrDefault(o => o.UserName == User.Identity.Name);

                Enrollment nullIfStudentDoesNotHaveThisCourse =
                    db.Enrollments.FirstOrDefault(
                        p => p.StudentID == thisStudent.StudentID && p.CourseID == course.CourseID);

                if (nullIfStudentDoesNotHaveThisCourse == null)
                {
                    if (course.Enrollments.Count < course.AttendanceCap)
                    {
                        CreateEnrollmentAttendanceAndNotificationData(course, thisStudent);
                        TempData["tempMessage"] =
                            "You have successfully enrolled in this Course. (Please note that the below details are default values until your Instructor updates them)";
                        return RedirectToAction("StudentDetails", "Attendance", new { id = course.CourseID });
                    }

                    return RedirectToAction("Message", new { message = "This course is full." });
                }

                return RedirectToAction("Message", new { message = "This student is already enrolled in this course." });
            }

            return RedirectToAction(
                "Message", 
                new
                    {
                        message =
                            "Course is not ready to be joined, it has not been approved by an Administrator or has already concluded."
                    });
        }

        public ActionResult ApproveCourse(int id)
        {
            Course course = db.Courses.Find(id);
            course.Approved = true;

            BuildNotificationData(course);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = course.CourseID });
        }

        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult Delete(int id)
        {
            Course course = db.Courses.Find(id);
            return View(course);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize(Roles = "Administrator, SuperAdministrator")]
        public ActionResult DeleteConfirmed(int id, Course hasReasonForDeletion)
        {
            Course course = db.Courses.Find(id);

            // Add the notification for the Instructor that their Course has been unapproved
            var newNotification = new Notification
                {

PaulSchool/Views/Student/Create.cshtml
@model PaulSchool.ViewModels.CreateStudentViewModel

@{
    ViewBag.Title = "Create Student";
}

<h2>Create Student</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Student</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstMidName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstMidName)
            @Html.ValidationMessageFor(model => model.FirstMidName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        @if (User.IsInRole("Administrator"))
        {
            <div class="editor-label">
                @Html.LabelFor(model => model.SelectedUser)
            </div>

            <div class="editor-field">
                @Html.LabelFor(x => x.SelectedUser)
                @Html.DropDownListFor(x => x.SelectedUser, Model.Users)
            </div>
        }
        else
        {
            <div class="editor-label">
                @Html.LabelFor(model => model.SelectedUser)
            </div>

            <div class="editor-field">
                @Html.TextBox("SelectedUser", User.Identity.Name)
            </div>
        }

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PaulSchool/Views/Student/Delete.cshtml
@model PaulSchool.Models.Student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Student</legend>

    <div class="display-label">LastName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">FirstMidName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstMidName)
    </div>

    <div class="display-label">Email</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">EnrollmentDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EnrollmentDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PaulSchool/Views/Student/Details.cshtml
@model PaulSchool.Models.Student

@{
    ViewBag.Title = "Student Details";
}

<h2>Student Details</h2>
<p>
    This is the total number of Core Classes Passed: @ViewBag.coresPassed ;  @ViewBag.coresNeeded core courses are needed to apply for Commissioning.
</p>
<p>
    This is the total number of Electives Passed: @ViewBag.electivesPassed ; @ViewBag.electivesNeeded electives are needed to apply for Commissioning.
</p>

<p>
    @Html.ActionLink("Apply for Commissioning", "Create", "Commissioning")
</p>

<fieldset>
    <legend>Student</legend>

    <p><b>Name:</b> @Html.DisplayFor(model => model.FirstMidName) @Html.DisplayFor(model => model.LastName)</p>

    <p><b>Email:</b> @Html.DisplayFor(model => model.Email) @Html.ActionLink("Send an email", "SendStudentAnEmail", new { emailAddress = Model.Email })</p>

    <p><b>Enrollment Date:</b> @Html.DisplayFor(model => model.EnrollmentDate)</p>

    <p><b>User Name:</b> @Html.DisplayFor(model => model.UserName)</p>
    
    <p><b>Address:</b></p>
        <div>
            @Html.DisplayFor(model => model.StreetAddress)<br>
                                                          @Html.DisplayFor(model => model.City), @Html.DisplayFor(model => model.State) @Html.DisplayFor(model => model.ZipCode)
        </div>
    
        <p><b>Phone:</b> @Html.DisplayFor(model => model.Phone)</p>
    
        <p><b>Date of Birth:</b> @Html.DisplayFor(model => model.DateOfBirth)</p>
    
        <p><b>Parish Affiliation:</b> @Html.DisplayFor(model => model.ParishAffiliation)</p>
    
        <p><b>Ministry Involvement:</b> @Html.DisplayFor(model => model.MinistryInvolvement)</p>
    
        @{
            if (ViewBag.mostRecentCommissioningCertificateID != null)
            {
                <p>
                    Certificate of Commissioning: @Html.ActionLink("view", "CertificateOfCommissioning", "Certificate", new {id = ViewBag.mostRecentCommissioningCertificateID}, null)
                </p>
            }
            else
            {
                <p>
                    Student is not Commissioned.
                </p>
            }
        }

    @{if (User.IsInRole("Administrator"))
      {
        <!--Admin Only Section - needs links to classes-->
        <div class="display-label">
        Class History as viewed by Admins
        </div>
        <div class="display-field">
        <table>
            <tr>
                <th>Course Title</th>
                <th>Grade</th>
                <th>Completion Date</th>
            </tr>
            @foreach (var item in Model.Enrollments)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Course.Title, "Details", "Course", new { id = item.Course.CourseID }, "a")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.EndDate)
                    </td>
                </tr>
            }
        </table>
        </div> 
      }
      else
      {
        <div class="display-label">
        Class History
        </div>
        <div class="display-field">
        <table>
            <tr>
                <th>Course Title</th>
                <th>Grade</th>
                <th>Completion Date</th>
            </tr>
            @foreach (var item in Model.Enrollments)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Grade)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.EndDate)
                    </td>
                </tr>
            }
        </table>
        </div>

      }
    }

</fieldset>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

PaulSchool/Views/Student/Index.cshtml
@model PagedList.IPagedList<PaulSchool.Models.Student>

@{
ViewBag.Title = "Students";
}

<h2>Students</h2>

<p>
@Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm())
{
<p>
    Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string) &nbsp;
    <input type="submit" value="Search" /></p>
}
<table>
<tr>
<th></th>
<th>
    @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
</th>
<th>
    @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FNameSortParm, currentFilter = ViewBag.CurrentFilter })
</th>
<th>
    @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.EmailSortParm, currentFilter = ViewBag.CurrentFilter })
</th>
<th>
    @Html.ActionLink("Enrollment Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
</th>
    <th>
        @Html.ActionLink("City", "Index", new { sortOrder = ViewBag.CitySortParm, currentFilter = ViewBag.CurrentFilter })
    </th>
    <th>
        @Html.ActionLink("ZipCode", "Index", new { sortOrder = ViewBag.ZipCodeSortParm, currentFilter = ViewBag.CurrentFilter })
    </th>
    <th>
        @Html.ActionLink("ParishAffiliation", "Index", new { sortOrder = ViewBag.ParishAffiliationSortParm, currentFilter = ViewBag.CurrentFilter })
    </th>
    <th>
        @Html.ActionLink("MinistryInvolvement", "Index", new { sortOrder = ViewBag.MinistryInvolvementSortParm, currentFilter = ViewBag.CurrentFilter })
    </th>
    <th>
    @Html.ActionLink("UserName", "Index", new { sortOrder = ViewBag.UserNameSortParm, currentFilter = ViewBag.CurrentFilter})
</th>
</tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.ActionLink("Details", "Details", new { id=item.StudentID })
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FirstMidName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EnrollmentDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.City)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ZipCode)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ParishAffiliation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MinistryInvolvement)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UserName)
    </td>
</tr>
}

</table>

<div>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
of @Model.PageCount
&nbsp;
@if (Model.HasPreviousPage)
{
    @Html.ActionLink("<<", "Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
    @Html.Raw("&nbsp;");
    @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
}
else
{
    @:<<
    @Html.Raw("&nbsp;");
    @:< Prev
}
&nbsp;
@if (Model.HasNextPage)
{
    @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
    @Html.Raw("&nbsp;");
    @Html.ActionLink(">>", "Index", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter=ViewBag.CurrentFilter  })
}
else
{
    @:Next >
    @Html.Raw("&nbsp;")
    @:>>
}
</div>

PaulSchool/Views/Student/SendStudentAnEmail.cshtml
@model PaulSchool.ViewModels.EmailViewModel

@{
    ViewBag.Title = "SendStudentAnEmail";
}

<h2>SendStudentAnEmail</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"> </script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"> </script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>EmailViewModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Subject)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Subject, new {style = "width:100%"})
            @Html.ValidationMessageFor(model => model.Subject)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body, new {style = "width:100%"})
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>