PaulSchool/Areas/MvcMembership/Models/UserAdministration/DetailsViewModel.cs
using System.Collections.Generic;
using System.Web.Security;

namespace SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration
{
	public class DetailsViewModel
	{
		#region StatusEnum enum

		public enum StatusEnum
		{
			Offline,
			Online,
			LockedOut,
			Unapproved
		}

		#endregion

		public string DisplayName { get; set; }
		public StatusEnum Status { get; set; }
		public MembershipUser User { get; set; }
		public bool CanResetPassword { get; set; }
		public bool RequirePasswordQuestionAnswerToResetPassword { get; set; }
		public IDictionary<string, bool> Roles { get; set; }
		public bool IsRolesEnabled { get; set; }
	}
}

PaulSchool/Models/InstructorApplication.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PaulSchool.Models
{
    public class InstructorApplication
    {
        public int InstructorApplicationID { get; set; }

        public int StudentID { get; set; }

        public virtual Student Student { get; set; }

        public List<EducationalBackground> EducationalBackground { get; set; }

        public string Experience { get; set; }

        [UIHint("IsChecked")]
        public bool WillingToTravel { get; set; }

        [UIHint("IsChecked")]
        public bool Approved { get; set; }
    }
}

PaulSchool/ViewModels/InstructorApplicationViewModel.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="InstructorApplicationViewModel.cs" company="LostTie LLC">
//   Copyright (c) Lost Tie LLC.  All rights reserved.
//   This code and information is provided "as is" without warranty of any kind, either expressed or implied, including but not limited to the implied warranties of merchantability and fitness for a particular purpose.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace PaulSchool.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using PaulSchool.Models;

    /// <summary>
    /// InstructorApplicationViewModel Class
    /// </summary>
    public class InstructorApplicationViewModel
    {
        /// <summary>
        /// Gets or sets EducationBackground
        /// </summary>
        public IList<EducationalBackGround> EducationalBackgrounds { get; set; }

        /// <summary>
        /// Gets or sets CurrentUserId
        /// </summary>
        public int CurrentUserId { get; set; }

        /// <summary>
        /// Gets or sets ExperienceList
        /// </summary>
        public SelectList ExperienceList { get; set; }

        /// <summary>
        /// Gets or sets Experience
        /// </summary>
        public string Experience { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether WillingToTravel
        /// </summary>
        public bool WillingToTravel { get; set; }
    }
}

PaulSchool/Controllers/StudentController.cs
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using PagedList;
using PaulSchool.Models;
using PaulSchool.ViewModels;

namespace PaulSchool.Controllers
{
    [Authorize(Roles = "Administrator, SuperAdministrator, Instructor")]
    public class StudentController : Controller
    {
        private readonly SchoolContext db = new SchoolContext();

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date desc" : "Date";
            ViewBag.FNameSortParm = sortOrder == "FName" ? "FName desc" : "FName";
            ViewBag.EmailSortParm = sortOrder == "Email" ? "Email desc" : "Email";
            ViewBag.CitySortParm = sortOrder == "City" ? "City desc" : "City";
            ViewBag.ZipCodeSortParm = sortOrder == "ZipCode" ? "ZipCode desc" : "ZipCode";
            ViewBag.ParishAffiliationSortParm = sortOrder == "ParishAffiliation" ? "ParishAffiliation desc" : "ParishAffiliation";
            ViewBag.MinistryInvolvementSortParm = sortOrder == "MinistryInvolvement" ? "MinistryInvolvement desc" : "MinistryInvolvement";
            ViewBag.UserNameSortParm = sortOrder == "UserName" ? "UserName desc" : "UserName";
            ViewBag.EnrollmentSortParm = sortOrder == "EnrollmentDate" ? "EnrollmentDate desc" : "EnrollmentDate";

            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }
            else
            {
                page = 1;
            }
            ViewBag.CurrentFilter = searchString;

            IQueryable<Student> students = from s in db.Students
                                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.LastName.ToUpper().Contains(searchString.ToUpper())
                                               || s.FirstMidName.ToUpper().Contains(searchString.ToUpper()));
            }
            //            city, zipcode, ministryinvolvement, parishaffiliation, username, enrollmentdate
            switch (sortOrder)
            {
                case "Name desc":
                    students = students.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.EnrollmentDate);
                    break;
                case "Date desc":
                    students = students.OrderByDescending(s => s.EnrollmentDate);
                    break;
                case "FName":
                    students = students.OrderBy(s => s.FirstMidName);
                    break;
                case "FName desc":
                    students = students.OrderByDescending(s => s.FirstMidName);
                    break;
                case "Email":
                    students = students.OrderBy(s => s.Email);
                    break;
                case "Email desc":
                    students = students.OrderByDescending(s => s.Email);
                    break;
                case "City":
                    students = students.OrderBy(s => s.City);
                    break;
                case "City desc":
                    students = students.OrderByDescending(s => s.City);
                    break;
                case "ZipCode":
                    students = students.OrderBy(s => s.ZipCode);
                    break;
                case "ZipCode desc":
                    students = students.OrderByDescending(s => s.ZipCode);
                    break;
                case "ParishAffiliation":
                    students = students.OrderBy(s => s.ParishAffiliation);
                    break;
                case "ParishAffiliation desc":
                    students = students.OrderByDescending(s => s.ParishAffiliation);
                    break;
                case "MinistryInvolvement":
                    students = students.OrderBy(s => s.MinistryInvolvement);
                    break;
                case "MinistryInvolvement desc":
                    students = students.OrderByDescending(s => s.MinistryInvolvement);
                    break;
                case "UserName":
                    students = students.OrderBy(s => s.UserName);
                    break;
                case "UserName desc":
                    students = students.OrderByDescending(s => s.UserName);
                    break;
                default:
                    students = students.OrderBy(s => s.LastName);
                    break;
            }
            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize));
        }

        public ViewResult StudentListWithAllDetails(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date desc" : "Date";
            ViewBag.FNameSortParm = sortOrder == "FName" ? "FName desc" : "FName";
            ViewBag.EmailSortParm = sortOrder == "Email" ? "Email desc" : "Email";
            ViewBag.UserNameSortParm = sortOrder == "City" ? "City desc" : "City";
            ViewBag.UserNameSortParm = sortOrder == "ZipCode" ? "ZipCode desc" : "ZipCode";
            ViewBag.UserNameSortParm = sortOrder == "ParishAffiliation" ? "ParishAffiliation desc" : "ParishAffiliation";
            ViewBag.UserNameSortParm = sortOrder == "MinistryInvolvement" ? "MinistryInvolvement desc" : "MinistryInvolvement";
            ViewBag.UserNameSortParm = sortOrder == "UserName" ? "UserName desc" : "UserName";
            ViewBag.UserNameSortParm = sortOrder == "EnrollmentDate" ? "EnrollmentDate desc" : "EnrollmentDate";

            if (Request.HttpMethod == "GET")
            {
                searchString = currentFilter;
            }
            else
            {
                page = 1;
            }
            ViewBag.CurrentFilter = searchString;

            IQueryable<Student> students = from s in db.Students
                                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.LastName.ToUpper().Contains(searchString.ToUpper())
                                               || s.FirstMidName.ToUpper().Contains(searchString.ToUpper()));
            }
            //            city, zipcode, ministryinvolvement, parishaffiliation, username, enrollmentdate
            switch (sortOrder)
            {
                case "Name desc":
                    students = students.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.EnrollmentDate);
                    break;
                case "Date desc":
                    students = students.OrderByDescending(s => s.EnrollmentDate);
                    break;
                case "FName":
                    students = students.OrderBy(s => s.FirstMidName);
                    break;
                case "FName desc":
                    students = students.OrderByDescending(s => s.FirstMidName);
                    break;
                case "Email":
                    students = students.OrderBy(s => s.Email);
                    break;
                case "Email desc":
                    students = students.OrderByDescending(s => s.Email);
                    break;
                case "City":
                    students = students.OrderBy(s => s.City);
                    break;
                case "City desc":
                    students = students.OrderByDescending(s => s.City);
                    break;
                case "ZipCode":
                    students = students.OrderBy(s => s.ZipCode);
                    break;
                case "ZipCode desc":
                    students = students.OrderByDescending(s => s.ZipCode);
                    break;
                case "ParishAffiliation":
                    students = students.OrderBy(s => s.ParishAffiliation);
                    break;
                case "ParishAffiliation desc":
                    students = students.OrderByDescending(s => s.ParishAffiliation);
                    break;
                case "MinistryInvolvement":
                    students = students.OrderBy(s => s.MinistryInvolvement);
                    break;
                case "MinistryInvolvement desc":
                    students = students.OrderByDescending(s => s.MinistryInvolvement);
                    break;
                case "UserName":
                    students = students.OrderBy(s => s.UserName);
                    break;
                case "UserName desc":
                    students = students.OrderByDescending(s => s.UserName);
                    break;
                default:
                    students = students.OrderBy(s => s.LastName);
                    break;
            }
            int pageSize = 25;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize));
        }

        public ViewResult Details(int id)
        {
            Student student = db.Students.Find(id);
            //ViewBag.testCompletedCoreCourses = (from o in student where o.enrollment)

            int totalCoresPassed = db.Enrollments.Count(s => s.StudentID == id
                                                             && s.Grade == "Credit Received"
                                                             && s.Course.Elective == false);

PaulSchool/Views/InstructorApplication/ApplyToBecomeInstructor.cshtml
@model PaulSchool.ViewModels.InstructorApplicationViewModel
@{
    ViewBag.Title = "Apply to Become an Instructor";
}
<h2>@PaulSchool.Resources.PaulSchoolResource.ApplyToBecomeInstructor_Text</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"> </script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"> </script>
<script src="@Url.Content("~/Scripts/EducationalBackgroundListEditor.js")" type="text/javascript"> </script>
@using (Html.BeginForm("ApplyToBecomeInstructor", "InstructorApplication", FormMethod.Post, new { @id = "appForm" }))
{
    <fieldset>
        <legend>@PaulSchool.Resources.PaulSchoolResource.ApplyToBecomeInstructor_Text</legend>
        <div class="editor-label">
            <p>@PaulSchool.Resources.PaulSchoolResource.Instructor_Information_Text</p>
        </div>
        @Html.HiddenFor(model => model.CurrentUserId)
        <div class="editor-label">
            <label for="EducationalBackgrounds">Educational Background</label>
        </div>
        <div class="editorRow-container">
            <h4>Every field should be complete (no blanks).</h4>
            <div id="editorRows">
                @Html.EditorFor(model => model.EducationalBackgrounds)
            </div>
        </div>
        @Html.ActionLink(@PaulSchool.Resources.PaulSchoolResource.Additional_background_Text, "EducationalBackground", null, new { id = "addItem" })
        <div class="editor-label">
            @Html.LabelFor(model => model.Experience)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Experience, Model.ExperienceList)
        </div>
        <div class="editor-label">
            @PaulSchool.Resources.PaulSchoolResource.Willing_travel_Text
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WillingToTravel)
        </div>
        <p>
            <input type="submit" value="Create" id="btnSubmit" />
        </p>
        <div class="newRow" style="display: none;">
            <div class="editorRow">
                @Html.EditorFor(model => model.EducationalBackgrounds)
            </div>
        </div>
    </fieldset>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>
<script type="text/javascript">
    instructorUrl = '@Url.Action("ApplyToBecomeInstructor", "InstructorApplication")';
    currentUser = '@Model.CurrentUserId';
</script>

PaulSchool/Views/InstructorApplication/Details.cshtml
@model PaulSchool.Models.InstructorApplication
@{
    ViewBag.Title = "Details";
}
<h2>
    Details</h2>
<fieldset>
    <legend>InstructorApplication</legend>
    
    <div class="display-label">Applicant's name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.FirstMidName) @Html.DisplayFor(model => model.Student.LastName)
        <p>
            You can click @Html.ActionLink("here", "Details", "Student", new { id = Model.StudentID }, null) to see the rest of the student's basic profile information.
        </p>
    </div>

    <div class="display-label">First Name and Middle Initial</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.FirstMidName)
    </div>
    
    <div class="display-label">Last Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.LastName)
    </div>

    <div class="display-label">Address</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.StreetAddress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.City) , @Html.DisplayFor(model => model.Student.State) @Html.DisplayFor(model => model.Student.ZipCode)
    </div>
    
    <div class="display-label">Phone and Email:</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.Phone) , @Html.DisplayFor(model => model.Student.Email)
    </div>
    
    <div class="display-label">Parish Affiliation</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Student.ParishAffiliation)
    </div>
    <div class="display-label">
        Education Details</div>
    @{foreach (var education in Model.EducationalBackground)
      { 
        <fieldset>
            <div class="display-label">
                UniversitOfCollege</div>
            <div class="display-field">@education.UniversityOrCollege
            </div>
            <div class="display-label">
                AreaOfStudy</div>
            <div class="display-field">@education.AreaOfStudy
            </div>
            <div class="display-label">
                Degree</div>
            <div class="display-field">@education.Degree
            </div>
            <div class="display-label">
                YearReceived</div>
            <div class="display-field">@education.YearReceived
            </div>
        </fieldset>
      }
    }
    <div class="display-label">
        Experience</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Experience)
    </div>
    <div class="display-label">
        Willing To Travel?</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WillingToTravel)
    </div>
     <div class="display-label">
        Approved?</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Approved)
    </div>
</fieldset>
<p>
    @{ if ((User.IsInRole("Administrator") || User.IsInRole("SuperAdministrator")) && Model.Approved == false)
       {
           <p>
               @Html.ActionLink("Clicking here will approve this Instructor's Application", "ApproveInstructorApplication", new { id = Model.InstructorApplicationID }, new { onclick = "return confirm('Are you sure you are ready to approve this application?  Doing so is not reversible.');" })
           </p>
           <p>
               @Html.ActionLink("Clicking here will deny and delete this Instructor's Application", "Delete", new { id = Model.InstructorApplicationID }, new { onclick = "return confirm('Are you sure you are ready to DELETE this application?  Doing so is not reversible.');" }) 
           </p>
        }
    }
    @Html.ActionLink("Back to List", "Index")
</p>

PaulSchool/Views/InstructorApplication/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>This is where you will apply to become an Instructor that is capable of applying to teach courses.</p>
@Html.ActionLink("Click here to apply to become an Instructor", "ApplyToBecomeInstructor")

PaulSchool/Views/InstructorApplication/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Success</h2>

<p>
    You have successfully approved the Instructor Application.
</p>

<p>
    @Html.ActionLink("Back to List of Instructor Applications", "Index")
</p>