PaulSchool/Areas/MvcMembership/Models/UserAdministration/CreateUserViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using DataAnnotationsExtensions;

namespace SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration
{
	public class CreateUserViewModel
	{
		[Display(Name = "User Name")]
		[Required]
		public string Username { get; set; }

		[Required, DataType(DataType.Password)]
		public string Password { get; set; }

		[Display(Name = "Password (Again...)")]
		[Required, DataType(DataType.Password)]
		public string ConfirmPassword { get; set; }

		[Display(Name = "Email Address")]
		[Required, Email]
		public string Email { get; set; }

		[Display(Name = "Secret Question")]
		public string PasswordQuestion { get; set; }

		[StringLength(100)]
		[Display(Name = "Secret Answer")]
		public string PasswordAnswer { get; set; }

		[Display(Name = "Initial Roles")]
		public IDictionary<string, bool> InitialRoles { get; set; }
	}
}

PaulSchool/Areas/MvcMembership/Models/UserAdministration/DetailsViewModel.cs
using System.Collections.Generic;
using System.Web.Security;

namespace SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration
{
	public class DetailsViewModel
	{
		#region StatusEnum enum

		public enum StatusEnum
		{
			Offline,
			Online,
			LockedOut,
			Unapproved
		}

		#endregion

		public string DisplayName { get; set; }
		public StatusEnum Status { get; set; }
		public MembershipUser User { get; set; }
		public bool CanResetPassword { get; set; }
		public bool RequirePasswordQuestionAnswerToResetPassword { get; set; }
		public IDictionary<string, bool> Roles { get; set; }
		public bool IsRolesEnabled { get; set; }
	}
}

PaulSchool/Areas/MvcMembership/Models/UserAdministration/IndexViewModel.cs
using System.Collections.Generic;
using System.Web.Security;
using PagedList;

namespace SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration
{
	public class IndexViewModel
	{
		public string Search { get; set; }
		public IPagedList<MembershipUser> Users { get; set; }
		public IEnumerable<string> Roles { get; set; }
		public bool IsRolesEnabled { get; set; }
	}
}

PaulSchool/Areas/MvcMembership/Models/UserAdministration/RoleViewModel.cs
using System.Collections.Generic;
using System.Web.Security;

namespace SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration
{
	public class RoleViewModel
	{
		public string Role { get; set; }
		public IDictionary<string, MembershipUser> Users { get; set; }
	}
}

PaulSchool/Areas/MvcMembership/Controllers/UserAdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;
using MvcMembership;
using MvcMembership.Settings;
using SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration;

namespace SampleWebsite.Mvc3.Areas.MvcMembership.Controllers
{
	[AuthorizeUnlessOnlyUser(Roles = "SuperAdministrator")] // allows access if you're the only user, only validates role if role provider is enabled
	public class UserAdministrationController : Controller
	{
		private const int PageSize = 10;
		private const string ResetPasswordBody = "Your new password is: ";
		private const string ResetPasswordSubject = "Your New Password";
		private readonly IRolesService _rolesService;
		private readonly ISmtpClient _smtpClient;
		private readonly IMembershipSettings _membershipSettings;
		private readonly IUserService _userService;
		private readonly IPasswordService _passwordService;

		public UserAdministrationController()
			: this(new AspNetMembershipProviderWrapper(), new AspNetRoleProviderWrapper(), new SmtpClientProxy())
		{
		}

		public UserAdministrationController(AspNetMembershipProviderWrapper membership, IRolesService roles, ISmtpClient smtp)
			: this(membership.Settings, membership, membership, roles, smtp)
		{
		}

		public UserAdministrationController(
			IMembershipSettings membershipSettings,
			IUserService userService,
			IPasswordService passwordService,
			IRolesService rolesService,
			ISmtpClient smtpClient)
		{
			_membershipSettings = membershipSettings;
			_userService = userService;
			_passwordService = passwordService;
			_rolesService = rolesService;
			_smtpClient = smtpClient;
		}

		public ActionResult Index(int? page, string search)
		{
			var users = string.IsNullOrWhiteSpace(search)
				? _userService.FindAll(page ?? 1, PageSize)
				: search.Contains("@")
					? _userService.FindByEmail(search, page ?? 1, PageSize)
					: _userService.FindByUserName(search, page ?? 1, PageSize);

			if (!string.IsNullOrWhiteSpace(search) && users.Count == 1)
				return RedirectToAction("Details", new {id = users[0].ProviderUserKey.ToString()});

			return View(new IndexViewModel
							{
								Search = search,
								Users = users,
								Roles = _rolesService.Enabled
									? _rolesService.FindAll()
									: Enumerable.Empty<string>(),
								IsRolesEnabled = _rolesService.Enabled
							});
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult CreateRole(string id)
		{
			if (_rolesService.Enabled)
				_rolesService.Create(id);
			return RedirectToAction("Index");
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult DeleteRole(string id)
		{
			_rolesService.Delete(id);
			return RedirectToAction("Index");
		}

		public ViewResult Role(string id)
		{
			return View(new RoleViewModel
							{
								Role = id,
								Users = _rolesService.FindUserNamesByRole(id)
													 .ToDictionary(
														k => k,
														v => _userService.Get(v)
													 )
							});
		}

		public ViewResult Details(Guid id)
		{
			var user = _userService.Get(id);
			var userRoles = _rolesService.Enabled
				? _rolesService.FindByUser(user)
				: Enumerable.Empty<string>();
			return View(new DetailsViewModel
							{
								CanResetPassword = _membershipSettings.Password.ResetOrRetrieval.CanReset,
								RequirePasswordQuestionAnswerToResetPassword = _membershipSettings.Password.ResetOrRetrieval.RequiresQuestionAndAnswer,
								DisplayName = user.UserName,
								User = user,
								Roles = _rolesService.Enabled
									? _rolesService.FindAll().ToDictionary(role => role, role => userRoles.Contains(role))
									: new Dictionary<string, bool>(0),
								IsRolesEnabled = _rolesService.Enabled,
								Status = user.IsOnline
											? DetailsViewModel.StatusEnum.Online
											: !user.IsApproved
												? DetailsViewModel.StatusEnum.Unapproved
												: user.IsLockedOut
													? DetailsViewModel.StatusEnum.LockedOut
													: DetailsViewModel.StatusEnum.Offline
							});
		}

		public ViewResult Password(Guid id)
		{
			var user = _userService.Get(id);
			var userRoles = _rolesService.Enabled
				? _rolesService.FindByUser(user)
				: Enumerable.Empty<string>();
			return View(new DetailsViewModel
			{
				CanResetPassword = _membershipSettings.Password.ResetOrRetrieval.CanReset,
				RequirePasswordQuestionAnswerToResetPassword = _membershipSettings.Password.ResetOrRetrieval.RequiresQuestionAndAnswer,
				DisplayName = user.UserName,
				User = user,
				Roles = _rolesService.Enabled
					? _rolesService.FindAll().ToDictionary(role => role, role => userRoles.Contains(role))
					: new Dictionary<string, bool>(0),
				IsRolesEnabled = _rolesService.Enabled,
				Status = user.IsOnline
							? DetailsViewModel.StatusEnum.Online
							: !user.IsApproved
								? DetailsViewModel.StatusEnum.Unapproved
								: user.IsLockedOut
									? DetailsViewModel.StatusEnum.LockedOut
									: DetailsViewModel.StatusEnum.Offline
			});
		}

		public ViewResult UsersRoles(Guid id)
		{
			var user = _userService.Get(id);
			var userRoles = _rolesService.FindByUser(user);
			return View(new DetailsViewModel
			{
				CanResetPassword = _membershipSettings.Password.ResetOrRetrieval.CanReset,
				RequirePasswordQuestionAnswerToResetPassword = _membershipSettings.Password.ResetOrRetrieval.RequiresQuestionAndAnswer,
				DisplayName = user.UserName,
				User = user,
				Roles = _rolesService.FindAll().ToDictionary(role => role, role => userRoles.Contains(role)),
				IsRolesEnabled = true,
				Status = user.IsOnline
							? DetailsViewModel.StatusEnum.Online
							: !user.IsApproved
								? DetailsViewModel.StatusEnum.Unapproved
								: user.IsLockedOut
									? DetailsViewModel.StatusEnum.LockedOut
									: DetailsViewModel.StatusEnum.Offline
			});
		}

		public ViewResult CreateUser()
		{
			var model = new CreateUserViewModel
			            	{
			            		InitialRoles = _rolesService.FindAll().ToDictionary(k => k, v => false)
			            	};
			return View(model);
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult CreateUser(CreateUserViewModel createUserViewModel)
		{
			if (!ModelState.IsValid)
				return View(createUserViewModel);

			try
			{
				if(createUserViewModel.Password != createUserViewModel.ConfirmPassword)
					throw new MembershipCreateUserException("Passwords do not match.");

				var user = _userService.Create(
					createUserViewModel.Username,
					createUserViewModel.Password,
					createUserViewModel.Email,
					createUserViewModel.PasswordQuestion,
					createUserViewModel.PasswordAnswer,
					true);

				if (createUserViewModel.InitialRoles != null)
				{
					var rolesToAddUserTo = createUserViewModel.InitialRoles.Where(x => x.Value).Select(x => x.Key);
					foreach (var role in rolesToAddUserTo)
						_rolesService.AddToRole(user, role);					
				}

				return RedirectToAction("Details", new { id = user.ProviderUserKey });
			}
			catch (MembershipCreateUserException e)
			{
				ModelState.AddModelError(string.Empty, e.Message);
				return View(createUserViewModel);
			}
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult Details(Guid id, string email, string comments)
		{
			var user = _userService.Get(id);
			user.Email = email;
			user.Comment = comments;
			_userService.Update(user);
			return RedirectToAction("Details", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult DeleteUser(Guid id)
		{
			var user = _userService.Get(id);

			if (_rolesService.Enabled)
				_rolesService.RemoveFromAllRoles(user);
			_userService.Delete(user);
			return RedirectToAction("Index");
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult ChangeApproval(Guid id, bool isApproved)
		{
			var user = _userService.Get(id);
			user.IsApproved = isApproved;
			_userService.Update(user);
			return RedirectToAction("Details", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult Unlock(Guid id)
		{
			_passwordService.Unlock(_userService.Get(id));
			return RedirectToAction("Details", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult ResetPassword(Guid id)
		{
			var user = _userService.Get(id);
			var newPassword = _passwordService.ResetPassword(user);

			var body = ResetPasswordBody + newPassword;
			var msg = new MailMessage();
			msg.To.Add(user.Email);
			msg.Subject = ResetPasswordSubject;
			msg.Body = body;
			_smtpClient.Send(msg);

			return RedirectToAction("Password", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult ResetPasswordWithAnswer(Guid id, string answer)
		{
			var user = _userService.Get(id);
			var newPassword = _passwordService.ResetPassword(user, answer);

			var body = ResetPasswordBody + newPassword;
			var msg = new MailMessage();
			msg.To.Add(user.Email);
			msg.Subject = ResetPasswordSubject;
			msg.Body = body;
			_smtpClient.Send(msg);

			return RedirectToAction("Password", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult SetPassword(Guid id, string password)
		{
			var user = _userService.Get(id);
			_passwordService.ChangePassword(user, password);

			var body = ResetPasswordBody + password;
			var msg = new MailMessage();
			msg.To.Add(user.Email);
			msg.Subject = ResetPasswordSubject;
			msg.Body = body;
			_smtpClient.Send(msg);

			return RedirectToAction("Password", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult AddToRole(Guid id, string role)
		{
			_rolesService.AddToRole(_userService.Get(id), role);
			return RedirectToAction("UsersRoles", new { id });
		}

		[AcceptVerbs(HttpVerbs.Post)]
		public RedirectToRouteResult RemoveFromRole(Guid id, string role)
		{
			_rolesService.RemoveFromRole(_userService.Get(id), role);
			return RedirectToAction("UsersRoles", new { id });
		}
	}
}

PaulSchool/Areas/MvcMembership/Views/UserAdministration/CreateUser.cshtml
@model SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration.CreateUserViewModel
@{
	ViewBag.Title = "Create New User";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />

<h2 class="mvcMembership">Create New User</h2>

<div class="mvcMembership-account">
	@using(Html.BeginForm("CreateUser", "UserAdministration")){ 
		@Html.ValidationSummary(true)
        <h1>WARNING</h1>
        <p>You should not be making a user here unless something has gone terribly wrong and you absolutely must create a user here.</p>
        <p>A user created here <strong>will not work appropriately</strong> with the rest of the application as is.</p>
        <p>In order to make a user that was created here function appropriately, the user <strong>must</strong> log-in and view the "Edit Profile" page, edit their profile, and save the changes <strong>before doing anything else</strong> on the web site.</p>
        <p>If the above step is not taken, a user created using this tool may cause great frustration for the Administration and Users of this web site.</p>
        <h4>Please proceed with caution</h4>
	 	<fieldset>
			@Html.EditorForModel()
		</fieldset>

		<fieldset>
			<h3 class="mvcMembership">Initial Roles</h3>
			@for(var i = 0; i < Model.InitialRoles.Count; i++){ 
				var role = Model.InitialRoles.ElementAt(i);
				<div>
					<input name="InitialRoles[@i].Key" type="hidden" value="@role.Key" />
					<label>@Html.CheckBox("InitialRoles[" + i + "].Value", role.Value) @role.Key</label>
				</div>
			}
		</fieldset>
	    <h4>Have you read the warning at the top of the page?  If you have read the warning and understand the risks involved in creating a user here, feel free to proceed.  If you do not understand - Do not proceed.</h4>
		<input type="submit" value="Create" />
	} 
</div>

PaulSchool/Areas/MvcMembership/Views/UserAdministration/Details.cshtml
@using System.Globalization
@model SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration.DetailsViewModel
@{
	ViewBag.Title = "User Details: " + Model.DisplayName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />

<h2 class="mvcMembership">User Details: @Model.DisplayName [@Model.Status]</h2>

<ul class="mvcMembership-tabs">
	<li>Details</li>
	<li>@Html.ActionLink("Password", "Password", "UserAdministration", new { id = Model.User.ProviderUserKey }, null)</li>
	@if(Model.IsRolesEnabled){
	<li>@Html.ActionLink("Roles", "UsersRoles", "UserAdministration", new { id = Model.User.ProviderUserKey }, null)</li>
	}
</ul>

<h3 class="mvcMembership">Account</h3>
<div class="mvcMembership-account">
	<dl class="mvcMembership">
		<dt>User Name:</dt>
			<dd>@Model.User.UserName</dd>
		<dt>Email Address:</dt>
			<dd><a href="mailto:@Model.User.Email">@Model.User.Email</a></dd>
		@if(Model.User.LastActivityDate == Model.User.CreationDate){
		<dt>Last Active:</dt>
			<dd><em>Never</em></dd>
		<dt>Last Login:</dt>
			<dd><em>Never</em></dd>
		}else{
		<dt>Last Active:</dt>
			<dd>@Model.User.LastActivityDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>
		<dt>Last Login:</dt>
			<dd>@Model.User.LastLoginDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>
		}
		<dt>Created:</dt>
			<dd>@Model.User.CreationDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>
	</dl>

	@using(Html.BeginForm("ChangeApproval", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
		@Html.Hidden("isApproved", !Model.User.IsApproved)
		<input type="submit" value='@(Model.User.IsApproved ? "Unapprove" : "Approve") Account' />
	}
	@using(Html.BeginForm("DeleteUser", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
		<input type="submit" value="Delete Account" />
	}
</div>

<h3 class="mvcMembership">Email Address & Comments</h3>
<div class="mvcMembership-emailAndComments">
	@using(Html.BeginForm("Details", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
	<fieldset>
		<p>
			<label for="email">Email Address:</label>
			@Html.TextBox("email", Model.User.Email)
		</p>
		<p>
			<label for="comments">Comments:</label>
			@Html.TextArea("comments", Model.User.Comment)
		</p>
		<input type="submit" value="Save Email Address and Comments" />
	</fieldset>
	}
</div>

PaulSchool/Areas/MvcMembership/Views/UserAdministration/Index.cshtml
@using PagedList.Mvc
@model SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration.IndexViewModel
@{
	ViewBag.Title = "User Administration";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />
<link href='@Url.Content("~/Content/PagedList.css")' rel="stylesheet" type="text/css" />

@if(!Model.IsRolesEnabled){
	<p class="mvcMembership-warning">WARNING: Your Role Provider is currently disabled - any user may currently visit this page.<br />Change &lt;roleManager enabled="false"&gt; to &lt;roleManager enabled="true"&gt; in your web.config file.</p>
}

<h2 class="mvcMembership">User Administration</h2>

<h3 class="mvcMembership">Find a User
	@if (!string.IsNullOrWhiteSpace(Model.Search)) { 
		<span>(@Html.ActionLink("Clear Search", "Index"))</span>
	}
</h3>
<form method="get" class="mvcMembership-searchForm">
	<fieldset>
		<label>
			User Name or Email Address:
			<input type="text" name="search" value="@Model.Search" />
			<input type="submit" value="Search" />
		</label>
	</fieldset>
</form>
	
<h3 class="mvcMembership">Users (@Html.ActionLink("New User", "CreateUser", "UserAdministration"))</h3>
<div class="mvcMembership-allUsers">
@if(Model.Users.Count > 0){
	<ul class="mvcMembership mvcMembership-users">
		@foreach(var user in Model.Users){
		<li>
			<span class="mvcMembership-username">@Html.ActionLink(user.UserName, "Details", new{ id = user.ProviderUserKey})</span>
			<span class="mvcMembership-email"><a href="mailto:@user.Email">@user.Email</a></span>
			@if(user.IsOnline){
				<span class="mvcMembership-isOnline">Online</span>
			}else{
				<span class="mvcMembership-isOffline">Offline for
					@{
						var offlineSince = (DateTime.Now - user.LastActivityDate);
						if (offlineSince.TotalSeconds <= 60){
							<text>1 minute.</text>
						}else if(offlineSince.TotalMinutes < 60){
							<text>@Math.Floor(offlineSince.TotalMinutes) minutes.</text>
						}else if (offlineSince.TotalMinutes < 120){
							<text>1 hour</text>
						}else if (offlineSince.TotalHours < 24){
							<text>@Math.Floor(offlineSince.TotalHours) hours.</text>
						}else if (offlineSince.TotalHours < 48){
							<text>1 day.</text>
						}else{
							<text>@Math.Floor(offlineSince.TotalDays) days.</text>
						}
					}
				</span>
			}
			@if(!string.IsNullOrEmpty(user.Comment)){
				<span class="mvcMembership-comment">@user.Comment</span>
			}
		</li>
		}
	</ul>
	@Html.PagedListPager(Model.Users, page => Url.Action("Index", new { page, search = Model.Search }))
}else{
	<p>No users have registered.</p>
}
</div>

@if(Model.IsRolesEnabled){
	<h3 class="mvcMembership">Roles</h3>
	<div class="mvcMembership-allRoles">
	@if(Model.Roles.Count() > 0 ){
		<ul class="mvcMembership">
			@foreach(var role in Model.Roles){
			<li>
				@Html.ActionLink(role, "Role", new{id = role})
				@using(Html.BeginForm("DeleteRole", "UserAdministration", new{id=role})){
				<input type="submit" value="Delete" />
				}
			</li>
			}
		</ul>
	}else{
		<p>No roles have been created.</p>
	}

	@using(Html.BeginForm("CreateRole", "UserAdministration")){
		<fieldset>
			<label for="id">Role:</label>
			@Html.TextBox("id")
			<input type="submit" value="Create Role" />
		</fieldset>
	}
	</div>
}

PaulSchool/Areas/MvcMembership/Views/UserAdministration/Password.cshtml
@using System.Globalization
@model SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration.DetailsViewModel
@{
	ViewBag.Title = "User Details: " + Model.DisplayName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />

<h2 class="mvcMembership">User Details: @Model.DisplayName [@Model.Status]</h2>

<ul class="mvcMembership-tabs">
	<li>@Html.ActionLink("Details", "Details", "UserAdministration", new {id = Model.User.ProviderUserKey }, null)</li>
	<li>Password</li>
	@if(Model.IsRolesEnabled){
	<li>@Html.ActionLink("Roles", "UsersRoles", "UserAdministration", new{id = Model.User.ProviderUserKey}, null)</li>
	}
</ul>

<h3 class="mvcMembership">Password</h3>
<div class="mvcMembership-password">
	@if(Model.User.IsLockedOut){
		<p>Locked out since @Model.User.LastLockoutDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</p>
		using(Html.BeginForm("Unlock", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
		<input type="submit" value="Unlock Account" />
		}
	}else{

		if(Model.User.LastPasswordChangedDate == Model.User.CreationDate){
		<dl class="mvcMembership">
			<dt>Last Changed:</dt>
			<dd><em>Never</em></dd>
		</dl>
		}else{
		<dl class="mvcMembership">
			<dt>Last Changed:</dt>
			<dd>@Model.User.LastPasswordChangedDate.ToString("MMMM dd, yyyy h:mm:ss tt", CultureInfo.InvariantCulture)</dd>
		</dl>
		}

		if(Model.CanResetPassword && Model.RequirePasswordQuestionAnswerToResetPassword){
			using(Html.BeginForm("ResetPasswordWithAnswer", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
			<fieldset>
				<p>
					<dl class="mvcMembership">
						<dt>Password Question:</dt>
						if(string.IsNullOrEmpty(Model.User.PasswordQuestion) || string.IsNullOrEmpty(Model.User.PasswordQuestion.Trim())){
						<dd><em>No password question defined.</em></dd>
						}else{
						<dd>@Model.User.PasswordQuestion</dd>
						}
					</dl>
				</p>
				<p>
					<label for="answer">Password Answer:</label>
					@Html.TextBox("answer")
				</p>
				<input type="submit" value="Reset to Random Password and Email User" />
			</fieldset>
			}
		}else if(Model.CanResetPassword){
			using(Html.BeginForm("SetPassword", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
			<fieldset>
				<p>
					<label for="password">New Password:</label>
					@Html.TextBox("password")
				</p>
				<input type="submit" value="Change Password" />
			</fieldset>
			}
			using(Html.BeginForm("ResetPassword", "UserAdministration", new{ id = Model.User.ProviderUserKey })){
			<fieldset>
				<input type="submit" value="Reset to Random Password and Email User" />
			</fieldset>
			}
		}

	}
</div>

PaulSchool/Areas/MvcMembership/Views/UserAdministration/Role.cshtml
@model SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration.RoleViewModel
@{
	ViewBag.Title = "Role: " + Model.Role;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />

<h2 class="mvcMembership">Role: @Model.Role</h2>
<div class="mvcMembership-roleUsers">
	@if(Model.Users.Count() > 0){
		<ul class="mvcMembership">
			@foreach(var key in Model.Users.Keys){ var user = Model.Users[key];
			<li>
				@if(user == null){
					<span>@key <em>(Deleted)</em></span>
				}else{
					@Html.ActionLink(user.UserName, "Details", new{id=user.ProviderUserKey})
					using(Html.BeginForm("RemoveFromRole", "UserAdministration", new{id = user.ProviderUserKey, role = Model.Role})){
						<input type="submit" value="Remove From" />
					}
				}
			</li>
			}
		</ul>
	}else{
	<p>No users are in this role.</p>
	}
</div>

PaulSchool/Areas/MvcMembership/Views/UserAdministration/UsersRoles.cshtml
@model SampleWebsite.Mvc3.Areas.MvcMembership.Models.UserAdministration.DetailsViewModel
@{
	ViewBag.Title = "User Details: " + Model.DisplayName;
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href='@Url.Content("~/Content/MvcMembership.css")' rel="stylesheet" type="text/css" />

<h2 class="mvcMembership">User Details: @Model.DisplayName [@Model.Status]</h2>

<ul class="mvcMembership-tabs">
	<li>@Html.ActionLink("Details", "Details", "UserAdministration", new { id = Model.User.ProviderUserKey }, null)</li>
	<li>@Html.ActionLink("Password", "Password", "UserAdministration", new { id = Model.User.ProviderUserKey }, null)</li>
	<li>Roles</li>
</ul>

<h3 class="mvcMembership">Roles</h3>
<div class="mvcMembership-userRoles">
	<ul class="mvcMembership">
		@foreach(var role in Model.Roles){
		<li>
			@Html.ActionLink(role.Key, "Role", new{id = role.Key})
			@if(role.Value){
				using(Html.BeginForm("RemoveFromRole", "UserAdministration", new{id = Model.User.ProviderUserKey, role = role.Key})){
				<input type="submit" value="Remove From" />
				}
			}else{
				using(Html.BeginForm("AddToRole", "UserAdministration", new{id = Model.User.ProviderUserKey, role = role.Key})){
				<input type="submit" value="Add To" />
				}
			}
		</li>
		}
	</ul>
</div>